/**
 * DialMyCalls API
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@dialmycalls.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DialmycallsJsClient);
  }
}(this, function(expect, DialmycallsJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DialmycallsJsClient.CreateCallParameters();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateCallParameters', function() {
    it('should create an instance of CreateCallParameters', function() {
      // uncomment below and update the code to test CreateCallParameters
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be.a(DialmycallsJsClient.CreateCallParameters);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property calleridId (base name: "callerid_id")', function() {
      // uncomment below and update the code to test the property calleridId
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property recordingId (base name: "recording_id")', function() {
      // uncomment below and update the code to test the property recordingId
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property machineRecordingId (base name: "machine_recording_id")', function() {
      // uncomment below and update the code to test the property machineRecordingId
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property sendAt (base name: "send_at")', function() {
      // uncomment below and update the code to test the property sendAt
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property sendImmediately (base name: "send_immediately")', function() {
      // uncomment below and update the code to test the property sendImmediately
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property useAmd (base name: "use_amd")', function() {
      // uncomment below and update the code to test the property useAmd
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property sendEmail (base name: "send_email")', function() {
      // uncomment below and update the code to test the property sendEmail
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property accessaccountId (base name: "accessaccount_id")', function() {
      // uncomment below and update the code to test the property accessaccountId
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property contacts (base name: "contacts")', function() {
      // uncomment below and update the code to test the property contacts
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

    it('should have the property addOns (base name: "add_ons")', function() {
      // uncomment below and update the code to test the property addOns
      //var instane = new DialmycallsJsClient.CreateCallParameters();
      //expect(instance).to.be();
    });

  });

}));
