/**
 * DialMyCalls API
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DialmycallsJsClient) {
      root.DialmycallsJsClient = {};
    }
    root.DialmycallsJsClient.CallRecipient = factory(root.DialmycallsJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CallRecipient model module.
   * @module Models/CallRecipient
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>CallRecipient</code>.
   * @alias module:Models/CallRecipient
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>CallRecipient</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Models/CallRecipient} obj Optional instance to populate.
   * @return {module:Models/CallRecipient} The populated <code>CallRecipient</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('firstname')) {
        obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
      }
      if (data.hasOwnProperty('miscellaneous')) {
        obj['miscellaneous'] = ApiClient.convertToType(data['miscellaneous'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('extension')) {
        obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Integer');
      }
      if (data.hasOwnProperty('add_on')) {
        obj['add_on'] = ApiClient.convertToType(data['add_on'], 'String');
      }
      if (data.hasOwnProperty('attempts')) {
        obj['attempts'] = ApiClient.convertToType(data['attempts'], 'String');
      }
      if (data.hasOwnProperty('successful')) {
        obj['successful'] = ApiClient.convertToType(data['successful'], 'Boolean');
      }
      if (data.hasOwnProperty('called_at')) {
        obj['called_at'] = ApiClient.convertToType(data['called_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * The recipient's first name.
   * @member {String} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * The recipient's last name.
   * @member {String} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * Miscellaneous information.
   * @member {String} miscellaneous
   */
  exports.prototype['miscellaneous'] = undefined;
  /**
   * The recipient's email address.
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * The recipient's phone number.
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * The recipient's phone extension.
   * @member {String} extension
   */
  exports.prototype['extension'] = undefined;
  /**
   * Status of the call. Options: live_answer, vm, busy, no_answer, dialing, not_connected, queued
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Duration of the call in seconds.
   * @member {Integer} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * Result from add-on feature.
   * @member {String} add_on
   */
  exports.prototype['add_on'] = undefined;
  /**
   * Number of attempts to call was made.
   * @member {String} attempts
   */
  exports.prototype['attempts'] = undefined;
  /**
   * Whether the call was successful or not.
   * @member {Boolean} successful
   */
  exports.prototype['successful'] = undefined;
  /**
   * When the recipient was contacted.
   * @member {String} called_at
   */
  exports.prototype['called_at'] = undefined;



  return exports;
}));


