/**
 * DialMyCalls API
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DialmycallsJsClient) {
      root.DialmycallsJsClient = {};
    }
    root.DialmycallsJsClient.Contact = factory(root.DialmycallsJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Contact model module.
   * @module Models/Contact
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>Contact</code>.
   * @alias module:Models/Contact
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>Contact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Models/Contact} obj Optional instance to populate.
   * @return {module:Models/Contact} The populated <code>Contact</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('firstname')) {
        obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
      }
      if (data.hasOwnProperty('miscellaneous')) {
        obj['miscellaneous'] = ApiClient.convertToType(data['miscellaneous'], 'String');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('extension')) {
        obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('extra1')) {
        obj['extra1'] = ApiClient.convertToType(data['extra1'], 'String');
      }
      if (data.hasOwnProperty('groups')) {
        obj['groups'] = ApiClient.convertToType(data['groups'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique identifier for this contact.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The contact's first name.
   * @member {String} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * The contact's last name.
   * @member {String} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * Miscellaneous information.
   * @member {String} miscellaneous
   */
  exports.prototype['miscellaneous'] = undefined;
  /**
   * The contact's phone number.
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * The contact's phone extension.
   * @member {String} extension
   */
  exports.prototype['extension'] = undefined;
  /**
   * The contact's email address.
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * Miscellaneous data about this contact.
   * @member {String} extra1
   */
  exports.prototype['extra1'] = undefined;
  /**
   * List of groups that this contact belongs to.
   * @member {String} groups
   */
  exports.prototype['groups'] = undefined;
  /**
   * When the contact was created.
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * When the contact was last updated.
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


