/**
 * DialMyCalls API
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DialmycallsJsClient) {
      root.DialmycallsJsClient = {};
    }
    root.DialmycallsJsClient.CreateRecordingByPhoneParameters = factory(root.DialmycallsJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateRecordingByPhoneParameters model module.
   * @module Models/CreateRecordingByPhoneParameters
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>CreateRecordingByPhoneParameters</code>.
   * @alias module:Models/CreateRecordingByPhoneParameters
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>CreateRecordingByPhoneParameters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Models/CreateRecordingByPhoneParameters} obj Optional instance to populate.
   * @return {module:Models/CreateRecordingByPhoneParameters} The populated <code>CreateRecordingByPhoneParameters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('callerid_id')) {
        obj['callerid_id'] = ApiClient.convertToType(data['callerid_id'], 'String');
      }
      if (data.hasOwnProperty('whitelabel')) {
        obj['whitelabel'] = ApiClient.convertToType(data['whitelabel'], 'Boolean');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('extension')) {
        obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
      }
    }
    return obj;
  }

  /**
   * (Required)  The name of the recording.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The caller id that the create recording message should be sent from.
   * @member {String} callerid_id
   */
  exports.prototype['callerid_id'] = undefined;
  /**
   * Add or remove the DialMyCalls intro message.
   * @member {Boolean} whitelabel
   */
  exports.prototype['whitelabel'] = undefined;
  /**
   * (Required)  The recipient's phone number who will record the message.
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * The recipient's phone extension up to 10 numeric digits.
   * @member {String} extension
   */
  exports.prototype['extension'] = undefined;



  return exports;
}));


