/**
 * DialMyCalls API
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DialmycallsJsClient) {
      root.DialmycallsJsClient = {};
    }
    root.DialmycallsJsClient.PushToTalk = factory(root.DialmycallsJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PushToTalk model module.
   * @module Models/PushToTalk
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>PushToTalk</code>.
   * @alias module:Models/PushToTalk
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>PushToTalk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Models/PushToTalk} obj Optional instance to populate.
   * @return {module:Models/PushToTalk} The populated <code>PushToTalk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('callerid_id')) {
        obj['callerid_id'] = ApiClient.convertToType(data['callerid_id'], 'String');
      }
      if (data.hasOwnProperty('ringtone')) {
        obj['ringtone'] = ApiClient.convertToType(data['ringtone'], 'String');
      }
      if (data.hasOwnProperty('cpm')) {
        obj['cpm'] = ApiClient.convertToType(data['cpm'], 'Integer');
      }
      if (data.hasOwnProperty('add_message')) {
        obj['add_message'] = ApiClient.convertToType(data['add_message'], Object);
      }
    }
    return obj;
  }

  /**
   * The add-on type. Option: ptt
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * Phone number to connect the caller to.
   * @member {String} callerid_id
   */
  exports.prototype['callerid_id'] = undefined;
  /**
   * The ringtone to play to the user when connecting. Options: elevator_music, caribbean_music, classical_music, digital_ringing, old_phone_ringing, goofy_music
   * @member {String} ringtone
   */
  exports.prototype['ringtone'] = undefined;
  /**
   * Calls per minute throttling.
   * @member {Integer} cpm
   */
  exports.prototype['cpm'] = undefined;
  /**
   * Add a generic add-on message.
   * @member {Object} add_message
   */
  exports.prototype['add_message'] = undefined;



  return exports;
}));


