/**
 * DialMyCalls API
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DialmycallsJsClient) {
      root.DialmycallsJsClient = {};
    }
    root.DialmycallsJsClient.UpdateVanityNumberByIdParameters = factory(root.DialmycallsJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UpdateVanityNumberByIdParameters model module.
   * @module Models/UpdateVanityNumberByIdParameters
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>UpdateVanityNumberByIdParameters</code>.
   * @alias module:Models/UpdateVanityNumberByIdParameters
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>UpdateVanityNumberByIdParameters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Models/UpdateVanityNumberByIdParameters} obj Optional instance to populate.
   * @return {module:Models/UpdateVanityNumberByIdParameters} The populated <code>UpdateVanityNumberByIdParameters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('call_options')) {
        obj['call_options'] = ApiClient.convertToType(data['call_options'], ['String']);
      }
      if (data.hasOwnProperty('recording_source')) {
        obj['recording_source'] = ApiClient.convertToType(data['recording_source'], 'String');
      }
      if (data.hasOwnProperty('specific_recording_id')) {
        obj['specific_recording_id'] = ApiClient.convertToType(data['specific_recording_id'], 'String');
      }
      if (data.hasOwnProperty('play_cta')) {
        obj['play_cta'] = ApiClient.convertToType(data['play_cta'], 'Boolean');
      }
      if (data.hasOwnProperty('ptt_number_id')) {
        obj['ptt_number_id'] = ApiClient.convertToType(data['ptt_number_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * The options to include when the number is called.  If an option is not included it will be turned off.  Option values should be boolean.  Possible values are: 'voicemail' (Leave A Message), 'ptt' (Push To Talk), 'optin' (Opt-In), 'repeat' (Repeat Your Message) -- Note: Optout cannot be removed without prior authorization.  Please contact customer support for this.
   * @member {Array.<String>} call_options
   */
  exports.prototype['call_options'] = undefined;
  /**
   * Where the recording will be generated from.  (specific, lastsent, lastuploaded)
   * @member {String} recording_source
   */
  exports.prototype['recording_source'] = undefined;
  /**
   * Unique identifier for the recording if recording_source is set to specific.
   * @member {String} specific_recording_id
   */
  exports.prototype['specific_recording_id'] = undefined;
  /**
   * Setting this to true our system will play the prompts for keys to be pushed.
   * @member {Boolean} play_cta
   */
  exports.prototype['play_cta'] = undefined;
  /**
   * This is a verified caller id that is on your account.  This will be used if PTT option is used.
   * @member {String} ptt_number_id
   */
  exports.prototype['ptt_number_id'] = undefined;



  return exports;
}));


