/**
 * DialMyCalls API
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DialmycallsJsClient) {
      root.DialmycallsJsClient = {};
    }
    root.DialmycallsJsClient.VerifyCallerIdByIdParameters = factory(root.DialmycallsJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VerifyCallerIdByIdParameters model module.
   * @module Models/VerifyCallerIdByIdParameters
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>VerifyCallerIdByIdParameters</code>.
   * @alias module:Models/VerifyCallerIdByIdParameters
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>VerifyCallerIdByIdParameters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Models/VerifyCallerIdByIdParameters} obj Optional instance to populate.
   * @return {module:Models/VerifyCallerIdByIdParameters} The populated <code>VerifyCallerIdByIdParameters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pin')) {
        obj['pin'] = ApiClient.convertToType(data['pin'], 'String');
      }
    }
    return obj;
  }

  /**
   * (Required)  Verification PIN number received from making add caller ID request.
   * @member {String} pin
   */
  exports.prototype['pin'] = undefined;



  return exports;
}));


